/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AModal: typeof import('./src/components/app/AModal.vue')['default']
    ComModal: typeof import('./src/components/intersection/ComModal.vue')['default']
    CommonModal: typeof import('./src/components/intersection/Common-modal.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    GlobeGl: typeof import('./src/components/web-gl/GlobeGl.vue')['default']
    GlobeGL: typeof import('./src/components/three-dimensional/GlobeGL.vue')['default']
    GlobeGlPOC: typeof import('./src/components/web-gl/GlobeGlPOC.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfinityScroll: typeof import('./src/components/intersection/InfinityScroll.vue')['default']
    ISPage: typeof import('./src/components/infinity-scroll/ISPage.vue')['default']
    Map: typeof import('./src/components/cqis/map.vue')['default']
    Modal: typeof import('./src/components/infinity-scroll/Modal.vue')['default']
    ModalPOC: typeof import('./src/components/infinity-scroll/ModalPOC.vue')['default']
    OptionCheck: typeof import('./src/components/intersection/OptionCheck.vue')['default']
    PagePOC: typeof import('./src/components/infinity-scroll/PagePOC.vue')['default']
    Popup: typeof import('./src/components/infinity-scroll/Popup.vue')['default']
    PopupPOC: typeof import('./src/components/infinity-scroll/PopupPOC.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeJs: typeof import('./src/components/web-gl/ThreeJs.vue')['default']
    ThreeJS: typeof import('./src/components/three-dimensional/ThreeJS.vue')['default']
    ThreeJsPOC: typeof import('./src/components/web-gl/ThreeJsPOC.vue')['default']
    Wiki: typeof import('./src/components/infinity-scroll/Wiki.vue')['default']
  }
}
