/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfinityScroll: typeof import('./src/components/intersection/InfinityScroll.vue')['default']
    OptionCheck: typeof import('./src/components/intersection/OptionCheck.vue')['default']
    Popup: typeof import('./src/components/intersection/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
